### ISSUE TITLE
hassUrl breaks the links

### ISSUE THREAD

**Issue by abeksis** [matt8707/ha-fusion#223]
thank you for the answer.

There seems to be a problem with the links of the cameras and other things.

in the log i get: 

`
SvelteKitError: Not found: /api/camera_proxy_stream/camera.warehouse
    at resolve2 (file:///rootfs/build/server/index.js:4027:18)
    at resolve (file:///rootfs/build/server/index.js:3859:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-hoE62lsD.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3857:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}

SvelteKitError: Not found: /local/liran.jpg
    at resolve2 (file:///rootfs/build/server/index.js:4027:18)
    at resolve (file:///rootfs/build/server/index.js:3859:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-hoE62lsD.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3857:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /local/plex_recently_added/plex/Plex_Recently_Added/f612.jpg
    at resolve2 (file:///rootfs/build/server/index.js:4027:18)
    at resolve (file:///rootfs/build/server/index.js:3859:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-hoE62lsD.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3857:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /local/plex_recently_added/plex/Plex_Recently_Added/p612.jpg
    at resolve2 (file:///rootfs/build/server/index.js:4027:18)
    at resolve (file:///rootfs/build/server/index.js:3859:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-hoE62lsD.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3857:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /api/hass_agent/media_player.avipc_win11/thumbnail.png
    at resolve2 (file:///rootfs/build/server/index.js:4027:18)
    at resolve (file:///rootfs/build/server/index.js:3859:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-hoE62lsD.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3857:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
`

![image](https://github.com/matt8707/ha-fusion/assets/10877299/eeb47749-4058-4b34-ba9c-73bbeea60530)

![image](https://github.com/matt8707/ha-fusion/assets/10877299/14dfc14b-cfd6-4152-b6ba-a20b466baf9e)

_Originally posted by @abeksis in https://github.com/matt8707/ha-fusion/discussions/222#discussioncomment-8190326_

**Comment by Plawasan** [comment]
The links point to the right URL but on the wrong port, i.e. 8099 (fusion) instead of 8123 (ha)
