### ISSUE TITLE
Weather icon missing

### ISSUE THREAD

**Issue by peter-ogden** [matt8707/ha-fusion#599]
Many evenings, our weather bureau returns an "unknown" value. This results in an error in the logs:

SvelteKitError: Not found: /weather/meteocons/unknown-night.svg
    at resolve2 (file:///rootfs/build/server/index.js:4168:18)
    at resolve (file:///rootfs/build/server/index.js:4001:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3999:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'

**Comment by knowald** [comment]
This is fixed in the maintained fork [knowald/ha-fusion](https://github.com/knowald/ha-fusion), released in [2026.7.0](https://github.com/knowald/ha-fusion/releases/tag/2026.7.0): when the weather entity state is `unknown` or `unavailable`, the sidebar widget now shows a placeholder instead of requesting a nonexistent icon.

Tracked in knowald/ha-fusion#2, fixed by knowald/ha-fusion@3b859ac.
