### ISSUE TITLE
Config resetting to default

### ISSUE THREAD

**Issue by Plawasan** [matt8707/ha-fusion#6]
Running 2023.12.3 as an addon, any changes I make disappear when I restart the addon, dashboard comes back empty with this error in the log:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
Listening on 0.0.0.0:5050
Error reading or parsing ./data/configuration.yaml: Error: ENOENT: no such file or directory, open './data/configuration.yaml'
    at async open (node:internal/fs/promises:633:25)
    at async readFile (node:internal/fs/promises:1242:14)
    at async loadFile (file:///rootfs/build/server/chunks/3-85oe4GFn.js:8:18)
    at async Promise.all (index 0)
    at async load (file:///rootfs/build/server/chunks/3-85oe4GFn.js:16:38)
    at async load_server_data (file:///rootfs/build/server/index.js:1891:18)
    at async file:///rootfs/build/server/index.js:3301:18 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './data/configuration.yaml'
}
```

**Comment by Harti33** [comment]
Having the same Problem


s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
Listening on 0.0.0.0:5050
Error reading or parsing ./data/dashboard.yaml: Error: ENOENT: no such file or directory, open './data/dashboard.yaml'
    at async open (node:internal/fs/promises:633:25)
    at async readFile (node:internal/fs/promises:1242:14)
    at async loadFile (file:///rootfs/build/server/chunks/3-sykjDTvk.js:8:18)
    at async Promise.all (index 1)
    at async load (file:///rootfs/build/server/chunks/3-sykjDTvk.js:16:38)
    at async load_server_data (file:///rootfs/build/server/index.js:1891:18)
    at async file:///rootfs/build/server/index.js:3301:18 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './data/dashboard.yaml'
}
Error reading or parsing ./data/configuration.yaml: Error: ENOENT: no such file or directory, open './data/configuration.yaml'
    at async open (node:internal/fs/promises:633:25)
    at async readFile (node:internal/fs/promises:1242:14)
    at async loadFile (file:///rootfs/build/server/chunks/3-sykjDTvk.js:8:18)
    at async Promise.all (index 0)
    at async load (file:///rootfs/build/server/chunks/3-sykjDTvk.js:16:38)
    at async load_server_data (file:///rootfs/build/server/index.js:1891:18)
    at async file:///rootfs/build/server/index.js:3301:18 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './data/configuration.yaml'
}

**Comment by notorioustubze** [comment]
Same issue:
Error reading or parsing ./data/dashboard.yaml: Error: ENOENT: no such file or directory, open './data/dashboard.yaml'
    at async open (node:internal/fs/promises:633:25)
    at async readFile (node:internal/fs/promises:1242:14)
    at async loadFile (file:///rootfs/build/server/chunks/3-aw3qjczk.js:8:18)
    at async Promise.all (index 1)
    at async load (file:///rootfs/build/server/chunks/3-aw3qjczk.js:16:38)
    at async load_server_data (file:///rootfs/build/server/index.js:1891:18)
    at async file:///rootfs/build/server/index.js:3301:18 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './data/dashboard.yaml'

**Comment by briiiian** [comment]
Having the same Problem

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
Listening on 0.0.0.0:5050
Error reading or parsing ./data/configuration.yaml: Error: ENOENT: no such file or directory, open './data/configuration.yaml'
    at async open (node:internal/fs/promises:633:25)
    at async readFile (node:internal/fs/promises:1242:14)
    at async loadFile (file:///rootfs/build/server/chunks/3-j8qz_UKp.js:8:18)
    at async Promise.all (index 0)
    at async load (file:///rootfs/build/server/chunks/3-j8qz_UKp.js:16:38)
    at async load_server_data (file:///rootfs/build/server/index.js:1891:18)
    at async file:///rootfs/build/server/index.js:3301:18 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './data/configuration.yaml'
}
Error reading or parsing ./data/dashboard.yaml: Error: ENOENT: no such file or directory, open './data/dashboard.yaml'
    at async open (node:internal/fs/promises:633:25)
    at async readFile (node:internal/fs/promises:1242:14)
    at async loadFile (file:///rootfs/build/server/chunks/3-j8qz_UKp.js:8:18)
    at async Promise.all (index 1)
    at async load (file:///rootfs/build/server/chunks/3-j8qz_UKp.js:16:38)
    at async load_server_data (file:///rootfs/build/server/index.js:1891:18)
    at async file:///rootfs/build/server/index.js:3301:18 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './data/dashboard.yaml'
}

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/releases/tag/2023.12.4
