### ISSUE TITLE
Only able to run HA-Fusion local

### ISSUE THREAD

**Issue by canedje** [matt8707/ha-fusion#82]
I only can use HA-Fusion on my local network.
Approaching by reverse Proxy (Nginx) is not working creating a connection error.
In de setup I changed the local IP to a Nginx DNS adress
For me not important (I only use it local on my tablet), but just to know
![image](https://github.com/matt8707/ha-fusion/assets/23150947/8910cc84-6427-417e-9842-9fe4101974b6)

**Comment by matt8707** [comment]
I'll close this for now, it could be a nginx setup error

**Comment by matze19999** [comment]
It's not a nginx error, I get the same error with traefik3 as reverse proxy. In the log, I get following error messages:

`SvelteKitError: Not found: /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
    at resolve2 (file:///rootfs/build/server/index.js:4062:18)
    at resolve (file:///rootfs/build/server/index.js:3894:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3892:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /server-status
    at resolve2 (file:///rootfs/build/server/index.js:4062:18)
    at resolve (file:///rootfs/build/server/index.js:3894:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3892:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /login.action
    at resolve2 (file:///rootfs/build/server/index.js:4062:18)
    at resolve (file:///rootfs/build/server/index.js:3894:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3892:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /_all_dbs
    at resolve2 (file:///rootfs/build/server/index.js:4062:18)
    at resolve (file:///rootfs/build/server/index.js:3894:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3892:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /.DS_Store
    at resolve2 (file:///rootfs/build/server/index.js:4062:18)
    at resolve (file:///rootfs/build/server/index.js:3894:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3892:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /.env
    at resolve2 (file:///rootfs/build/server/index.js:4062:18)
    at resolve (file:///rootfs/build/server/index.js:3894:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3892:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /.git/config
    at resolve2 (file:///rootfs/build/server/index.js:4062:18)
    at resolve (file:///rootfs/build/server/index.js:3894:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3892:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /s/235323e2430323e2632323e2233313/_/;/META-INF/maven/com.atlassian.jira/jira-webapp-dist/pom.properties
    at resolve2 (file:///rootfs/build/server/index.js:4062:18)
    at resolve (file:///rootfs/build/server/index.js:3894:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3892:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /config.json
    at resolve2 (file:///rootfs/build/server/index.js:4062:18)
    at resolve (file:///rootfs/build/server/index.js:3894:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3892:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /telescope/requests
    at resolve2 (file:///rootfs/build/server/index.js:4062:18)
    at resolve (file:///rootfs/build/server/index.js:3894:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3892:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /.git/config
    at resolve2 (file:///rootfs/build/server/index.js:4062:18)
    at resolve (file:///rootfs/build/server/index.js:3894:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3892:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}`

No entity states are shown over reverse proxy:

![image](https://github.com/matt8707/ha-fusion/assets/13684520/591dceba-93ec-4fc1-b534-73540c24e5f9)

**Comment by matze19999** [comment]
@matt8707 can you please re-open the issue because it's not a reverse proxy problem?

**Comment by matt8707** [comment]
Can you post information on how to replicate this step-by-step?

**Comment by matt8707** [comment]
Thanks. I understand how it works in theory, but I'm seeking detailed, step-by-step instructions to avoid spending time on research when replicating the issue.

**Comment by kenhoppla** [comment]
Having the same issue with using cloudflared

**Comment by Nartsuto** [comment]
I had the same issue and when you inspect the page I was seeing something like "Mixed Content" & "was loaded over https, but requested an insecure frame" (I'm thinking http)

So I assumed the issue was a mix match of the http and https configs and the only http I had between the three services (traefik3, hassio and fusion) was the environement variable for fusion to talk to home assistant. 

So I tried pointing fusion at my external address (https://homeassistant.domain.com) rather than my local address (Http://ip:port) for home assistant and can now access fusion through my external domain (https://fusion.domain.com) without the errors you are seeing.

![image](https://github.com/user-attachments/assets/d0e8818f-3027-4cc6-a99f-4d27766f1d04)
